spring:
     datasource:
     #oracle
        driverClassName: oracle.jdbc.OracleDriver  
        druid:
            first:  #数据源1
                url: jdbc:oracle:thin:@192.168.77.32:1521:orcl11
                username: hbzw_app
                password: 123456
            second:  #数据源2
                url: jdbc:oracle:thin:@192.168.77.32:1521:orcl11
                username: hbzw_app
                password: 123456
            initial-size: 10
            max-active: 30
            min-idle: 25
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
     redis:
       open: true  # 是否开启redis缓存  true开启   false关闭
       database: 0
       password:      # 密码（默认为空）
       timeout: 6000  # 连接超时时长（毫秒）
       cluster:
           nodes: 192.168.77.189:7001,192.168.77.190:7001,192.168.77.191:7001,192.168.77.192:7001,192.168.77.193:7001,192.168.77.194:7001,192.168.77.195:7001,192.168.77.196:7001,192.168.77.197:7001,192.168.77.198:7001,192.168.77.199:7001,192.168.77.200:7001,192.168.77.201:7001,192.168.77.202:7001,192.168.77.203:7001,192.168.77.204:7001
       jedis: 
         pool:
             max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
             max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
             max-idle: 10      # 连接池中的最大空闲连接
             min-idle: 5       # 连接池中的最小空闲连接
logging:
  file: /home/hbzw_back_java.log 